### ISSUE TITLE
Docker usage instructions?

### ISSUE THREAD

**Issue by mizz141** [TurboCheetah/sneedex-indexer#61]
I'm trying to run V1.1 with AnimeBytes support inside a docker container on unraid, I've set-up the compose and linked it with Prowlarr,
![image](https://user-images.githubusercontent.com/20839616/205453326-ce113676-b226-4c87-97bf-b8bb5e593a4f.png)

I've provided it with an API key and the test button results in a valid response.

the logs show that responses are being sent to prowlarr, and 200 OK statuses are returned

However, there are no results when trying to make a search through prowlarr
![image](https://user-images.githubusercontent.com/20839616/205443212-27e599ee-fcaa-4ddf-ab0b-7772d8fba561.png)

And this error shows inside the logs:
```
Script error "start" exited with 139 status
$ bun run src/index.ts
12 |     const sneedexData = await fetch(
13 |       `${SNEEDEX_URL}/search?key=${this.apiKey}&c=50&q=${encodeURIComponent(
14 |         query
15 |       )}`
16 |     ).then(res => {
17 |       if (!res.ok) throw new Error(res.statusText)
```

Also, how is AnimeBytes integration planned? would it be possible to add docker variables for username and passkey?

**Comment by TurboCheetah** [comment]
The indexer itself does not need an API key, sorry if that was a bit confusing due to the project name. All of the API keys are stored in a `.env` file, which Bun reads using dotenv. I ran into issues trying to add the environment variables directly within the docker compose file, hence the need to have it pull in the `.env` file. Apologies for not including an example file, I thought I had.

The reason as to why testing the indexer in Prowlarr is returning a 200 is because I was just returning dummy data. I'll add a check to ensure that all the required keys for the indexers used are present before returning a 200 and having it throw an error with what needs to be fixed. 

I just added some stuff to the README regarding this issue, hopefully it clears things up. Feel free to close this issue if it has resolved your questions.

**Comment by mizz141** [comment]
The readme helped quite a bit, thanks for that

altough I'm still getting this error inside the logs when performing a search, and constant segfaults even when restarting.

![image](https://user-images.githubusercontent.com/20839616/205453052-23ee2f87-4840-4eed-9c28-9fa2196e0f62.png)

**Comment by mizz141** [comment]
I think I figured it out, forgot to update the compose file.

**Comment by mizz141** [comment]
Thanks, it's working fine now, animebytes integration also seems to be working.
